Repository GDSC-DGU/gdsc-dgu, pull requests merged in 2024-04, with the labels that each got.

#11 ✨Feat : 네브바 생성, 기본 레이아웃 설정
  src/app/(home)/page.tsx
  src/app/community/page.tsx
  src/app/layout.tsx
  src/app/member/page.tsx
  src/app/page.tsx
  src/app/project/page.tsx
  src/app/recruit/page.tsx
  src/app/seminar/[id]/page.tsx
  src/app/seminar/page.tsx
  src/app/timeline/page.tsx
  src/components/navigation.tsx
Labels: ⚙️ Setting, 🙋‍♂️ 희찬, ✨ Feature

#18 ✨Feat: 타임라인 페이지 완성
  public/images/timeline_img.png
  src/app/timeline/page.tsx
  src/components/timeline/button/GenerationButton.tsx
  src/components/timeline/card/TimelineCard.tsx
  src/components/timeline/header/DateHeader.tsx
  src/components/timeline/header/TimelineHeader.tsx
  src/components/timeline/part/TimelineMonthlyPart.tsx
  src/components/timeline/section/TimelineMonthlyCardSection.tsx
  src/constants/timeline/timelineCardInfo.ts
  src/interfaces/timeline/timelineCard.ts
  src/interfaces/timeline/timelineCardList.ts
  src/interfaces/timeline/timelineDate.ts
  src/interfaces/timeline/timelineGeneration.ts
  src/utils/timeline/formDate.ts
  src/utils/timeline/groupByMonthYear.ts
Labels: 🙋‍♂️ 도형, ✨ Feature

#20 ✨Feat: 메인페이지 레이아웃 완성
  public/images/main/story_ex.png
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/components/home/.keep
  src/components/home/aboutGDSC/AboutGDSC.tsx
  src/components/home/aboutGDSCDGU/AboutGDSCDGU.tsx
  src/components/home/activity/Activity.tsx
  src/components/home/banner/HomeBanner.tsx
  src/components/home/moreAbout/MoreAbout.tsx
  src/components/home/storiesFrom/StoriesFrom.tsx
  src/components/home/title/HomeTitle.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🙋‍♀️ 서현

#21 Feat: 멤버 페이지 구현
  public/images/member_banner.png
  public/images/members/lead.png
  public/svg/icons/member/futureCircle.svg
  public/svg/icons/member/futureDotLine.svg
  public/svg/icons/member/shortDotLine.svg
  public/svg/member_header.svg
  src/app/member/page.tsx
  src/components/member/generation/GenerationPage.tsx
  src/components/member/header/MemberHeader.tsx
  src/components/member/introduce/LeadIntro.tsx
  src/components/member/introduce/MemberIntro.tsx
  src/components/member/profilebox/ProfileBox.tsx
  src/components/member/timeline/TimeLine.tsx
  src/constants/member/.keep
  src/constants/member/AIML.ts
  src/constants/member/devRel.ts
  src/constants/member/serverCloud.ts
  src/constants/member/timeLine.ts
  src/constants/member/webApp.ts
  tailwind.config.ts
Labels: ✨ Feature, 🙋‍♀️ 현정
