Repository GDSC-DGU/gdsc-dgu, pull requests merged in 2024-05, with the labels that each got.

#32 ✨Feat: Timeline 피드백 반영, Footer 제작, 폰트, 색상, 반응형 적용
  public/svg/icons/common/right_arrow.svg
  src/app/layout.tsx
  src/app/timeline/page.tsx
  src/components/layout/.keep
  src/components/layout/footer/Footer.tsx
  src/components/timeline/button/GenerationButton.tsx
  src/components/timeline/card/TimelineCard.tsx
  src/components/timeline/header/DateHeader.tsx
  src/components/timeline/header/TimelineHeader.tsx
  src/components/timeline/part/TimelineMonthlyPart.tsx
  src/components/timeline/section/TimelineMonthlyCardSection.tsx
  src/constants/member/timeLine.ts
  src/constants/timeline/timelineCardInfo.ts
  src/styles/globals.css
  src/utils/timeline/groupByMonthYear.ts
Labels: 🎨 Design, 🔨 Refactor, 🙋‍♂️ 도형, ✨ Feature

#37 [✨Feature] Project Feedback 반영, 모션 라이브러리 적용
  package-lock.json
  package.json
  src/app/project/[id]/page.tsx
  src/app/project/page.tsx
  src/app/solutionChallenge/page.tsx
  src/components/project/card/ProjectCard.tsx
  src/components/project/content/ProjectContent.tsx
  src/components/project/content/ProjectMember.tsx
  src/components/project/content/ProjectToggle.tsx
  src/components/project/header/ProjectHeader.tsx
  src/components/project/introduction/ProjectIntroduction.tsx
  src/components/project/introduction/ProjectIntroductionBand.tsx
  src/components/project/list/ProjectDesktopList.tsx
  src/components/project/list/ProjectList.tsx
  src/components/project/list/ProjectMobileList.tsx
  src/components/project/pagination/ProjectPagination.tsx
  src/components/sollutionChallenge/header/SolutionChallengeHeader.tsx
  src/components/sollutionChallenge/list/SolutionChallengeList.tsx
  src/components/sollutionChallenge/tab/SolutionChallengeTab.tsx
  src/constants/project/projects.ts
  src/constants/project/slideUpVariants.ts
  src/interfaces/project/projectData.ts
  src/interfaces/project/projectMemberData.ts
  src/styles/globals.css
  src/utils/project/toggle.ts
Labels: 🎨 Design, 🔨 Refactor, ✨ Feature, 🙋‍♀️ 나경

#36 💄Design: 색상 및 텍스트 크기 적용 #35
  public/svg/recruit_banner2.svg
  src/components/navigation.tsx
  src/components/recruit/faq/RecruitFaq.tsx
  src/components/recruit/faq/RecruitFaqBox.tsx
  src/components/recruit/header/RecruitHeader.tsx
  src/components/recruit/part/RecruitPartKeyword.tsx
  src/components/recruit/part/RecruitPartRow.tsx
  src/components/recruit/recommand/RecruitRecommand.tsx
  src/components/recruit/schedule/RecruitSchedule.tsx
  src/components/recruit/schedule/RecruitScheduleBox.tsx
  src/components/recruit/target/RecruitTarget.tsx
  src/components/recruit/target/RecruitTargetRowText.tsx
Labels: 🎨 Design, 🔨 Refactor, 🙋‍♂️ 희찬

#39 Feature/28
  package-lock.json
  package.json
  public/images/main/aboutGDSC_map.png
  src/app/layout.tsx
  src/components/home/aboutGDSC/AboutGDSC.tsx
  src/components/home/activity/Activity.tsx
  src/components/home/storiesFrom/StoriesFrom.tsx
  src/components/navigation.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🙋‍♀️ 서현

#48 [✨Feature] 세미나 애니메이션 추가, 노션 연결, pdf 다운 추가
  next.config.mjs
  package.json
  public/images/seminar/default_open_seminar.png
  public/images/seminar/default_seminar.png
  public/images/seminar/presenter/default_presenter.png
  public/images/seminar/translate_img.png
  src/app/api/member/route.tsx
  src/app/api/seminar/all/route.tsx
  src/app/api/seminar/open/info/route.tsx
  src/app/api/seminar/open/route.tsx
  src/app/api/seminar/review/route.tsx
  src/app/api/seminar/route.tsx
  src/app/seminar/[id]/page.tsx
  src/app/seminar/open/[id]/page.tsx
  src/app/seminar/page.tsx
  src/components/seminar/header/SeminarHeader.tsx
  src/components/seminar/menubar/SeminarMenuBar.tsx
  src/components/seminar/openSeminarDetail/banner/OpenSeminarDetailBanner.tsx
  src/components/seminar/openSeminarDetail/header/OpenSeminarDetailHeader.tsx
  src/components/seminar/openSeminarDetail/information/OpenSeminarDetailInformation.tsx
  src/components/seminar/openSeminarDetail/kindOfSeminar/OpenSeminarDetailSeminars.tsx
  src/components/seminar/openSeminarDetail/kindOfSeminar/OpenSeminarsDetailBox.tsx
  src/components/seminar/seminarDetail/banner/SeminarDetailBanner.tsx
  src/components/seminar/seminarDetail/banner/SeminarDetailBannerInform.tsx
  src/components/seminar/seminarDetail/header/SeminarDetailHeader.tsx
  src/components/seminar/seminarDetail/pdf/SeminarDetailPdf.tsx
  src/components/seminar/seminarDetail/review/SeminalDetailReviewDetail.tsx
  src/components/seminar/seminarDetail/review/SeminarDetailReview.tsx
  src/components/seminar/thumbnail/SeminarPagination.tsx
  src/components/seminar/thumbnail/SeminarThumbnail.tsx
  src/components/seminar/thumbnail/SeminarThumbnailList.tsx
  src/components/seminar/toggle/SeminarToggle.tsx
  src/components/seminar/toggle/SeminarToggleMenu.tsx
  src/constants/seminar/openSeminarData.ts
  src/constants/seminar/seminarCardVariants.ts
  src/constants/seminar/seminarData.ts
  src/constants/seminar/seminarMemberData.ts
  src/constants/seminar/seminarReviewData.ts
  src/constants/seminar/seminarToggleVariants.ts
  src/hooks/seminar/changePathtoNumber.ts
  src/hooks/seminar/changePathtoNumber.tsx
  src/hooks/seminar/notionDataRefactor.ts
  src/interfaces/seminar/openSeminar.ts
  src/interfaces/seminar/seminarMember.ts
  src/interfaces/seminar/seminarReview.ts
  src/interfaces/seminar/seminarThumbnail.ts
Labels: ✨ Feature

#50 [✨Feature] Footer 최종, 타임라인 카드 반응형 수정
  src/components/layout/footer/Footer.tsx
  src/components/timeline/button/CreatorLinkButton.tsx
  src/components/timeline/part/TimelineMonthlyPart.tsx
Labels: 🙋‍♂️ 도형, ✨ Feature

#54 [feature]mainpage 애니메이션, 이미지 추가
  public/GDSC-logo.gif
  public/GDSC-logo_out.gif
  src/components/home/aboutGDSC/AboutGDSC.tsx
  src/components/home/aboutGDSCDGU/AboutGDSCDGU.tsx
  src/components/home/activity/Activity.tsx
  src/components/home/animation/animaiton.tsx
  src/components/home/banner/HomeBanner.tsx
  src/components/home/moreAbout/MoreAbout.tsx
  src/components/home/storiesFrom/StoriesFrom.tsx
  src/components/home/title/HomeTitle.tsx
  src/components/navigation.tsx
  tailwind.config.ts
Labels: ✨ Feature
